{% set version = "1.28.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-future
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/future_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/future/future_{{ version }}.tar.gz
  sha256: 6fdda66acd9a255e5baa70ff5dacd3c57ab2ecc2d87fd6abeebdfb939c051bf6

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-globals >=0.13.1
    - r-listenv >=0.8.0
    - r-parallelly >=1.21.0
  run:
    - r-base
    - r-digest
    - r-globals >=0.13.1
    - r-listenv >=0.8.0
    - r-parallelly >=1.21.0

test:
  commands:
    - $R -e "library('future')"           # [not win]
    - "\"%R%\" -e \"library('future')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/future
  license: LGPL-2.1-or-later
  summary: The purpose of this package is to provide a lightweight and unified Future API for sequential and parallel processing of R expression via futures.  The simplest way to evaluate an expression in parallel is to use `x %<-% { expression }` with `plan(multiprocess)`. This package implements sequential, multicore,
    multisession, and cluster futures.  With these, R expressions can be evaluated on the local machine, in parallel a set of local machines, or distributed on a mix of local and remote machines. Extensions to this package implement additional backends for processing futures via compute cluster schedulers etc. Because of
    its unified API, there is no need to modify any code in order switch from sequential on the local machine to, say, distributed processing on a remote compute cluster. Another strength of this package is that global variables and functions are automatically identified and exported as needed, making it straightforward
    to tweak existing code to make use of futures.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: future
# Version: 1.13.0
# Title: Unified Parallel and Distributed Processing in R for Everyone
# Imports: digest, globals (>= 0.12.4), listenv (>= 0.7.0), parallel, utils
# Suggests: R.rsp, markdown
# VignetteBuilder: R.rsp
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Description: The purpose of this package is to provide a lightweight and unified Future API for sequential and parallel processing of R expression via futures.  The simplest way to evaluate an expression in parallel is to use `x %<-% { expression }` with `plan(multiprocess)`. This package implements sequential, multicore, multisession, and cluster futures.  With these, R expressions can be evaluated on the local machine, in parallel a set of local machines, or distributed on a mix of local and remote machines. Extensions to this package implement additional backends for processing futures via compute cluster schedulers etc. Because of its unified API, there is no need to modify any code in order switch from sequential on the local machine to, say, distributed processing on a remote compute cluster. Another strength of this package is that global variables and functions are automatically identified and exported as needed, making it straightforward to tweak existing code to make use of futures.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# ByteCompile: TRUE
# URL: https://github.com/HenrikBengtsson/future
# BugReports: https://github.com/HenrikBengtsson/future/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-08 19:44:17 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2019-05-08 22:50:03 UTC
