{% set version = "1.34.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-future
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/future_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/future/future_{{ version }}.tar.gz
  sha256: 5839d4fd1f8beb1b18b27a7c50c1eb2bb5d80acd926b1bce9323637c8b2dfa5d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-globals >=0.16.1
    - r-listenv >=0.8.0
    - r-parallelly >=1.34.0
  run:
    - r-base
    - r-digest
    - r-globals >=0.16.1
    - r-listenv >=0.8.0
    - r-parallelly >=1.34.0

test:
  commands:
    - $R -e "library('future')"           # [not win]
    - "\"%R%\" -e \"library('future')\""  # [win]

about:
  home: https://future.futureverse.org/
  dev_url: https://github.com/HenrikBengtsson/future
  license: LGPL-2.1-or-later
  summary: The purpose of this package is to provide a lightweight and unified Future API for sequential and parallel processing of R expression via futures.  The simplest way to evaluate an expression in parallel is to use `x %<-% { expression }` with `plan(multiprocess)`. This package implements sequential, multicore,
    multisession, and cluster futures.  With these, R expressions can be evaluated on the local machine, in parallel a set of local machines, or distributed on a mix of local and remote machines. Extensions to this package implement additional backends for processing futures via compute cluster schedulers etc. Because of
    its unified API, there is no need to modify any code in order switch from sequential on the local machine to, say, distributed processing on a remote compute cluster. Another strength of this package is that global variables and functions are automatically identified and exported as needed, making it straightforward
    to tweak existing code to make use of futures.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
